### ISSUE TITLE
Add prefix to an image url?

### ISSUE THREAD

**Issue by badtant** [webpack/file-loader#102]
So, I have this name config:
`name=/build/images/[hash].[ext]`
Which will copy my images to the build folder.

For a few reasons I then have my server to serve the build folder at /xxx-folder/build.
But my files will be requested from /build/file.jpg (because of my config) instead of /xxx-folder/build/file.jpg

Is there some way for me to configure so that the files are still put in the build folder but requested from /xxx-folder/build/ ?
Some kind of prefix...

**Comment by SpaceK33z** [comment]
See #81

**Comment by badtant** [comment]
ahh, sorry
