### ISSUE TITLE
Zip file fails if configured in require/import

### ISSUE THREAD

**Issue by oakley808** [webpack/file-loader#103]
I have a zip file that can be included successfully via:
```
import myfile from 'assets/LatestDocumentation.zip'
// downloads as [hashed_name].zip
```
But when I try to preserve the filename like:
```
import myfile from 'file?name=SomeOfficialName.zip!assets/LatestDocumentation.zip'
```
It downloads as a corrupt zip on a PC, and a zip that extracts as a `.cpgz` file on a Mac. 

Is it possible to configure zip files to download and without hashing the filename?

**Comment by SpaceK33z** [comment]
Looking to your first example, it seems that you also have configured `file-loader` via your `webpack.config.js` file. In that case, the second example would be ran through the file-loader two times. You'd probably need to do this: `!!file?name=SomeOfficialName.zip!assets/LatestDocumentation.zip`.

**Comment by oakley808** [comment]
That was exactly the right fix! Thank you @SpaceK33z
