### ISSUE TITLE
File-Loader not copying all image files over

### ISSUE THREAD

**Issue by allencoded** [webpack/file-loader#116]
I am running the latest file loader config like so:

```
            {
                test: /\.(png|jpeg|jpg|gif)$/,
                use: [
                  {
                    loader: 'file-loader',
                    options: {
                      name: 'images/[path][name].[ext]',
                      context: './images'
                    }
                  }
                ]
            },
```

But I am only getting a partial amount of my images and not getting them all. For instance:
logo-qb-header-sm.png doesn't copy over. Yet 1/2 the other ones in that folder do. 

```
                    Asset     Size  Chunks                    Chunk Names
        images/leaves.jpg   226 kB          [emitted]         
  images/audi-vintage.jpg   400 kB          [emitted]  [big]  
        images/snacks.jpg   288 kB          [emitted]  [big]  
      images/audi-80s.jpg  54.9 kB          [emitted]         
       images/audi-a3.jpg  47.6 kB          [emitted]         
      images/audi-add.jpg   106 kB          [emitted]         
     images/audi-dash.jpg   168 kB          [emitted]         
        images/coffee.jpg  9.46 kB          [emitted]         
           images/dog.jpg  9.84 kB          [emitted]         
    images/herbert@4x.png    21 kB          [emitted]         
     images/landscape.jpg   151 kB          [emitted]         
        images/flower.jpg   239 kB          [emitted]         
images/painted-ladies.jpg   297 kB          [emitted]  [big]  
    images/tall-image.png   420 kB          [emitted]  [big]  
            app.bundle.js  6.35 MB       0  [emitted]  [big]  app
        aurelia.bundle.js   923 kB       1  [emitted]  [big]  aurelia
               global.css   488 kB       0  [emitted]  [big]  app
        app.bundle.js.map  8.17 MB       0  [emitted]         app
           global.css.map   1.1 MB       0  [emitted]         app
    aurelia.bundle.js.map   1.1 MB       1  [emitted]         aurelia
              favicon.ico  1.15 kB          [emitted]         
               index.html  1.16 kB          [emitted]         
```

Is there something wrong with what I am doing or understanding here? Shouldn't it just copy over all files in the images that have the extension png/jpeg/jpg/gif right? I am not seeing any errors printed out

**Comment by SpaceK33z** [comment]
Do you require the images that are not included in your JS code? It will only include those

**Comment by allencoded** [comment]
Ah yeah just learned that. Thanks will close this.

**Comment by chrisj-skinner** [comment]
@SpaceK33z I have the same issue - could you give an example of `require / import` the images.
Thanks

**Comment by loftyet** [comment]
@chrisj-skinner found this one on stackoverflow
`
https://stackoverflow.com/questions/39458511/how-to-use-es6-import-for-images
`

**Comment by cbernardes** [comment]
The problem is if you want your assets based on configuration and dynamic folders.

It turned out that building a White Label application is harder than I imagine.

1 - I don't import my images cause I don't want them to be a burden to my bundle.
2 - I don't reference them directly because they directly because they could come from my repo or from S3 for example and this path is completely configurable on my app.

It would be nice if I could inform the path of images and have them copied from there. For now the solution is using CopyWebpackPlugin.

**Comment by AssouaAlbert** [comment]
An we keep going through tutorial ans I dont think I saw one person adding an import.
