### ISSUE TITLE
file-loader works in require but not configure

### ISSUE THREAD

**Issue by ninjascience** [webpack/file-loader#13]
The file loader works from a require statement in a js file 

```
require('file!./../fonts/olivier.ttf');
```

but not when the webpack config is setup to use the file loader on ttf files

```
module.exports = {
  plugins: [
    new ComponentPlugin(),
    new webpack.ProvidePlugin({
      "_": "lodash",
      $: "jquery",
      jQuery: "jquery",
      "windows.jQuery": "jquery"
    })
  ],
  loaders: [
    { test: /\.ttf$/, loader: "file" },
    { test: /\.css$/,
      loader: "style-loader!css-loader" },
    { test: /\.less$/,
      loader: "style-loader!css-loader!less-loader"
    }
  ]
};
```

This setup gives this error:
```
ERROR in ./public/fonts/olivier.ttf
Module parse failed: /Users/rmil19/workspace/metric/public/fonts/olivier.ttf Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./public/js/main.js 5:0-33
```

**Comment by cgreening** [comment]
You probably fixed your issue - but I think it shold be:

{ test: /\.ttf$/, loader: "file-loader" },

**Comment by sokra** [comment]
This should work. Everyone does it this way.

**Comment by giovannipiller** [comment]
Had a very similar issue, and "solved" it by moving all non-js loaders into `preLoaders`.

First time using webpack, so it's very likely that I did something wrong.

Everything always worked when manually specifying the loader during a `require(...)`, or when adding `--module-bind "png=file-loader"` while using webpack's CLI.

**Comment by giovannipiller** [comment]
Yeah, don't mind me. Apparently I had `loader: [...]` instead of `loaders: [...]`.
..... I know

**Comment by SpaceK33z** [comment]
Closing this very old issue since, as has been said, everybody uses it this way and it works. If there still is an issue, feel free to comment.
