### ISSUE TITLE
How to specify a directory (not a file) 

### ISSUE THREAD

**Issue by codeuniquely** [webpack/file-loader#15]
Right now I have the following, with more to come.

    require("file?name=[path][name].[ext]&context=./src!./img/logo.png");
    require("file?name=[path][name].[ext]&context=./src!./img/bg.png");
    require("file?name=[path][name].[ext]&context=./src!./img/envelope.png");
    require("file?name=[path][name].[ext]&context=./src!./img/camera-black.png");

And this creates the img/ folder in the build folder as expected and populates it with the four files.

The reason we do this is, because the folder is shared buy a number of customers who develop their own custom modules and don't often use webPack - but do put their files / folders into the src/img folder for automated building.

So there are things like  

     /img/cust1/*.*
     /img/cust2/*.*
     /img/cust3/*.*
     /img/cust4/*.*
   
What i was trying to do was bundle them in one go when we build the site / tenants rather than having to pipe all the directory listing into a file and then globally replace parts of the path with the requires section and run macros to fix the line endings. I have to do this every time a new file is added, so it just gets done manually as part of the build every time regardless - just in case there is another files or a file that been removed

I tried doing all of these but I get must be a 'file' or 'directory' errors.
 
    require("file?name=[path][name].[ext]&context=./src!./img/**");
    require("file?name=[path][name].[ext]&context=./src!./img/**/");
    require("file?name=[path][name].[ext]&context=./src!./img/**/*.png");
    require("file?name=[path][name].[ext]&context=./src!./img/");
    require("file?name=[path][name].[ext]&context=./src!./img");
    require("file?name=[path][name].[ext]&context=./src!./cust1/*.*");
    require("file?name=[path][name].[ext]&context=./src!./cust1/");

How do you specify a "directory" like the error messages says you can ?

**Comment by sokra** [comment]
You shouldn't use webpack to (just) copy your files. require the images where they are used.

**Comment by codeuniquely** [comment]
@sokra - OK sounds good, 

So say that I'm using React.JS and I have this component definition that I would normal write as

    module.exports = React.createClass({
      displayName: 'Notification',
      applyStyle: function() {
        this.props.style = {
          position: "absolute",
          width: 100,
          height: 60,
          minWidth: 100,
          top: 0,
          right: 200,
          background: "url(/img/envelope.png) 0 0 no-repeat",
          cursor:"pointer"
        };
      },
      render: function () {
        this.applyStyle();
        return React.createElement('section', this.props, badge);
      }
    });

If I insert a line before the module.exports that goes something like?

    var png = require("file?name=[path][name].[ext]&context=./src!../../img/envelope.png");

and then I can change the line referencing the png to: 

    background: "url("+png+") 0 0 no-repeat",

So I guess my question is, does it matter any more what the file is named and would a more general hash type requires just be a better idea?

**Comment by sokra** [comment]
It doesn't matter how it's named and the default is pretty good.

You shouldn't write loaders inline. Better put them in your config. http://webpack.github.io/docs/using-loaders.html#configuration

`var png = require("../../img/envelope.png");`

**Comment by codeuniquely** [comment]
OK - that look seven better and much easier to write the requires like that anyway ...

**Comment by codeuniquely** [comment]
OK I added a loader in the webpack.config.js 

     { test: /\.jpe?g$|\.gif$|\.png$/i, loader: "file" },

and i get the following error messages on rebuilt: (webpack-dev-server)
````
ERROR in (desktop) ./src/img/envelope.png
Module parse failed: F:\Projects\Reactify\src\img\envelope.png Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./src/js/components/Notification.react.js 12:10-43
````

but if I just do a command line

    webpack   

the file is written to the build folder (in this case as).

    cc2b54823b17c401ae4933285c5454d2.png

**Comment by sokra** [comment]
`webpack.config.js` is only used for CLI. When you use the node.js API `require("./webpack.config.js")`

**Comment by codeuniquely** [comment]
I'm not using node, I'm just building a JavaScript based browser app using react. The files, index.html , bundle.js and the few image files will just be put in a root folder of some web server at a later date. right now i just using "webpack-dev-server"

I just run a command line of  "webpack-dev-server --progress --colors"
And when it starts I just then edit the code and save, and the browser refreshes.

I'm sorry but I don't understand what you're trying to get me to do. I'm not even sure i understand what that means anyway.

**Comment by sokra** [comment]
Sorry for the confusion.. I missread your comment.

I'm I right that you get different results for `webpack-dev-server` and `webpack`?

**Comment by codeuniquely** [comment]
yes i did - which confused me..  

I've been playing around with the webpack.config.js and I just got it working

### what I did was: 

    { test: /\.jpe?g$|\.gif$|\.png$/i, loader: "file" },

(working for "webpack" only and failing in "webpack-dev-server")


### but when I did this:

    { test: /\.jpe?g$|\.gif$|\.png$/i, loader: "file-loader" },

it works for both "webpack" and "webpack-dev-server"

it's now doing a great job pulling in all the images across various pages as I edit and save, 
:+1:

**Comment by sokra** [comment]
huh... That's pretty weird. Are both `webpack-dev-server` and `webpack` installed locally in your project

**Comment by codeuniquely** [comment]
```
"devDependencies": {
    "css-loader": "^0.9.1",
    "extract-text-webpack-plugin": "^0.3.8",
    "file-loader": "^0.8.1",
    "html-loader": "^0.2.3",
    "html-webpack-plugin": "^1.1.0",
    "json-loader": "^0.5.1",
    "minimist": "^1.1.0",
    "sass-loader": "^0.3.1",
    "style-loader": "^0.8.3",
    "typescript-loader": "^1.0.0",
    "url-loader": "^0.5.5"
    "webpack": "^1.5.3",
    "webpack-dev-server": "^1.7.0"
  }
```

**Comment by sokra** [comment]
I don't know...

**Comment by codeuniquely** [comment]
no worries, like a said by adding the -loader it all work exceptionally well - nice product by the way.

**Comment by mathieumg** [comment]
> You shouldn't use webpack to (just) copy your files. require the images where they are used.

@sokra We have the following use case: We use a 3rd-party npm module that is a React component used to display country flags. The component provides the 2,000 country flags alongside it and refers to them using a path (that can be overridden). Wouldn't that be a case where we want to "copy" the flags folder to the build using Webpack? It would be technically equivalent to "requiring" them one after one, but done automatically based on the current file structure.

**Comment by owais** [comment]
@mathieumg Interesting use case. Did you find a solution within the webpack eco-system? My use case is somewhat similar. 

@sokra 
I've to refer to assets (images) from HTML pages webpack doesn't know about and can't load/parse so I can't "require" the images in those pages. Right now, I've to import those images inside a CSS or JS file so webpack copies them over. How would we fix that?

**Comment by owais** [comment]
For now I'm doing it like this,
```
require("my-module/images/" + /^.*$/);
```

Is there a better way?

**Comment by mathieumg** [comment]
@owais No solution yet, I have the sideproject of writing a plugin.

**Comment by SpaceK33z** [comment]
Closing this since it is outside the scope of file-loader and this issue has been inactive for a very long time. Feel free to create a new issue with a more specific issue.

**Comment by DoubleU23** [comment]
@owais 
thx for the suggestion... but it doesn't work at my stack
`Error: Cannot find module './/^.*$/'.`
