### ISSUE TITLE
emitFile is required from module system

### ISSUE THREAD

**Issue by sterlingwes** [webpack/file-loader#2]
Curious why an error is thrown for this. Should it not fail silently (or still warn), but at least return the same path to the file and just not call `emitFile`?

I noticed the issue raised over at `enhanced-require`:  https://github.com/webpack/enhanced-require/issues/3, and I understand why, but here's my use case:

I'm using webpack via the Node.js API to server-side render a site built heavily with [React](facebook.github.io/react). In order to benefit from the server-side rendering, the client side code must render the same thing when the React component is mounted to the DOM. Using `require('url!mylogo.png');` renders the logo fine but where `emitFile` can't be used I need to at least get the same path to the image for the React client side rendering to match the prerender from the server.

In order to get this to work properly I amended the loader as follows:
-   Remove error thrown when no emitFile present (ie: via node api / enhanced-require)
-   Check for emitFile and don't call it if it's not there

I also had to set `__webpack_public_path__` at runtime if it was not set to avoid an issue there.

Then it works. Hopefully you understand the React bit. I can see why you might want to alert the user but for my purposes it helps if the loader fails silently when emitFile is not present.

**Comment by SpaceK33z** [comment]
Is this issue still relevant? It's been two years :).

**Comment by Cap32** [comment]
@SpaceK33z checkout https://github.com/webpack/file-loader/pull/33

**Comment by SpaceK33z** [comment]
Closing since it was fixed a while ago (use `emitFile=false`).
