### ISSUE TITLE
Unexpected character

### ISSUE THREAD

**Issue by barbalex** [webpack/file-loader#24]
Hi

I'm very new to webpack and loading files so probably I'm completely off and please correct me.
I have loaded dozens of png images in my site without problem.
With one (access2.png) I constantly get this error message:

    > gs@1.0.0 start C:\Users\alex\gs
    > webpack-dev-server

    C:\Users\alex\gs\node_modules\babel-core\lib\babel\transformation\file\index.js:600
          throw err;
                ^
    SyntaxError: C:/Users/alex/gs/images/access2.png: Unexpected character '´┐¢' (1:0)
    > 1 | ´┐¢PNG
        | ^
      2 | ←[7m→←[27m
      3 | ←[7m

    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "s
    tart"
    npm ERR! node v0.12.3
    npm ERR! npm  v2.9.1
    npm ERR! code ELIFECYCLE
    npm ERR! gs@1.0.0 start: `webpack-dev-server`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the gs@1.0.0 start script 'webpack-dev-server'.
    npm ERR! This is most likely a problem with the gs package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     webpack-dev-server
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls gs
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\alex\gs\npm-debug.log

I can link this file without loading it over webpack and it works fine.

Is this a problem with file-loader?

I attached the image file below.
The Image is loaded here: https://github.com/barbalex/gs/blob/master/src/pages/public.js#L5
Loading is configured here: https://github.com/barbalex/gs/blob/master/webpack.config.js#L35-40

Alex
![access2](https://cloud.githubusercontent.com/assets/669783/7714668/a43f38c4-fe80-11e4-86f3-3c42d8d25ff3.png)

**Comment by sokra** [comment]
I don't think it's a problem with the file-loader. It looks like you are running the babel transformation agains the png file. Looks like from a normal node.js `require` (not webpack processed). Propably from another (template?) loader.

**Comment by barbalex** [comment]
hm. One day later it works. Seemingly without changing anything. I hate magic... sorry for the noise

**Comment by mwelche** [comment]
i've been running into this same error with babel & file-loader but haven't been blessed with the same magic fix

**Comment by sokra** [comment]
You may get this issue because the file-loader is not correctly applied.

i. e. because of an incorrect `test` or a typo in the configuration names.

**Comment by jdart** [comment]
I'm having this issue as well but only when running react components with the mocha test framework, and only for one require of a png - some work fine. Webpack is cut out of the picture in this case, so I'm not sure how more things don't fail. Anyway I worked around the issue by using [ignore-styles](https://github.com/bkonkle/ignore-styles) and adding the file extensions like png.

**Comment by thevangelist** [comment]
@jdart Can you share your solution?

**Comment by jdart** [comment]
@thevangelist: in mochaSetup.js I added the below:

```javascript
import register from 'ignore-styles';
register(['.css', '.styl', '.png']);
```

**Comment by thevangelist** [comment]
@jdart how do you use that mochaSetup.js in package.json's test script?

**Comment by jdart** [comment]
@thevangelist Are you having trouble with a third party library, or is this your project's package.json? If it's your project, then you'll have to find some js that's executed by the test script, and add the snippet - mochaSetup.js is an arbitrary file, sorry it wasn't helpful to mention it specifically. If it's a third party library you're probably out of luck and should open an issue in the library github.

**Comment by thevangelist** [comment]
@jdart that's my own package.json yes, I'm just unsure how to pass the file to mocha

**Comment by thevangelist** [comment]
@jdart solved it by doing: "--require ./mocha-setup.js"
