### ISSUE TITLE
Sub Directory entry points

### ISSUE THREAD

**Issue by talves** [webpack/file-loader#3]
I am using multiple entry points to create my modules.  My index.html files for each entry point are in different paths.  I did not want to separate my modules into new webpack projects, but I need them to be able to stand alone later as their own root entry.
The entries are setup like the following:
- ./main.js (./index.html)
- ./admin/main.js (./admin/index.html)
- ./anotherentry/main.js (./anotherentry/index.html)

I have actually solved any public path issues during webpack-dev-server by setting
- `output.publicPath = '/'` when running the webpack-dev-server
- `output.publicPath = ''` when running webpack

The problem I have with file-loader now is that it always emits the file to a relative path to the context and also sets the url to the path from the context root which means the path points to the incorrect place for the entry points in the sub directories.

Here is how I think file-loader should handle the path of the url's.
- have an emitUrl based on the `options.context` 
- have a url based on `query.context || this.options.context` as the root and pass context in parameters if in a sub directory. I am not sure there is a way to know if your entry is in your current directory.
- if the public path is absolute (i.e. this.options.output.publicPath.substr(0,1) === '/') then the emitUrl and url are the same and paths do not need to be different

If you think I am going down the wrong road with this, please let me know.  Otherwise, I think I could put together a PR to show you what I mean.

**Comment by philipheyde** [comment]
Thank you @sokra. Your reply helped me greatly!

**Comment by SpaceK33z** [comment]
Closing since it looks like the root problem has been solved now. If there's still a problem, please make a new issue.
