### ISSUE TITLE
Method for specifying include paths for files (e.g. node_modules)

### ISSUE THREAD

**Issue by benvinegar** [webpack/file-loader#40]
I have a rule in a CSS file that references a file loaded from an npm module (in node_modules) ... but I cannot find a way to have file-loader locate this file, unless I make it relative, e.g. `../../../../node_modules/module/image.png`.

It would be nice if there was a way to tell file-loader to treat node_modules as an include path. 

As a point of comparison, it appears that sass-loader [lets you do this](https://github.com/jtangelder/sass-loader#sass-options).

**Comment by SimenB** [comment]
https://github.com/webpack/css-loader#usage

Use `~` before the path to indicate it's a module

**Comment by SpaceK33z** [comment]
Closing since the question has been answered.

**Comment by cjke** [comment]
Is there a way to specify include paths that _aren't_ node_modules? The original question simply suggested node_modules as an example, but is there a way to mark certain include paths (much like the sass loaded does)? 

Alternatively, should file-loader respect the `resolve` config item?

(let me know if you want a seperate issue)
