### ISSUE TITLE
file-loader combined with bundle-loader or require.ensure ends up skipping the file.

### ISSUE THREAD

**Issue by prasannavl** [webpack/file-loader#43]
> sample.js

`require.ensure([], function(require) {
 require("./app");
});
`
> config

`loaders: [{
                    test: /\.js[x]?$/i,
                    loader: "file?name=js/[hash].js!babel",
                    exclude: /node_modules/
                },
`

Now this ends up skipping the parsing of the `./app` which, in this scenario will be the main file, and outputs the bundle with sample.js file `as is`.

**Comment by SpaceK33z** [comment]
Do you still have this issue? A lot of time has passed ;).

**Comment by prasannavl** [comment]
@SpaceK33z, I suppose. But as you said, a long time has passed :) .. Around that time, I abstracted out things out to use custom codepaths to handle what I needed. I am not sure if this issue still valid with webpack 2.

**Comment by SpaceK33z** [comment]
All right. I'm closing this issue since it doesn't seem like an issue we can fix in file-loader (if it's even still there), and nobody else seems to have it. Feel free to re-open with more information if you happen to get it.

**Comment by prasannavl** [comment]
Fair enough :)
