### ISSUE TITLE
Add ability to copy over a whole directory with random files

### ISSUE THREAD

**Issue by priyajeet** [webpack/file-loader#44]
I am trying to copy a bunch of static files (can be any type including binaries, so not just js/css/html, but like .bin/.obj etc.) from the source folder to output directory. I cannot find a way to properly do this with the file loader, unsure if it is possible:

```javascript
// src.js
import '/path/to/third-party/vendor/directory';
```

```javascript
// webpack.config.js
{
    test: path.join(__dirname, '/path/to/third-party/vendor/directory'),
    loader: 'file-loader?name=[path][name].[ext]'
}
```

Is it possible with the file loader? I looked at https://github.com/webpack/webpack/issues/525 however the method in that doesn't seem to work unless I am doing something wrong.

**Comment by jorgecas99** [comment]
Same issue here. For us Public is generated via Java Maven so it would be awesome if we can copy files over to public dir when we run webpack via pom. Can file-loader handle this via webpack-config? example will be very much appreciated.

**Comment by priyajeet** [comment]
Personally I gave up on using file loader for this use case and just using rsync now as follows by creating a mini webpack rsync plugin.

```javascript
function RsyncPlugin(source, destination) {
    this.source = source;
    this.destination = destination;
}
RsyncPlugin.prototype.apply = function(compiler) {
    var self = this;
    compiler.plugin('done', function() {
        exec('rsync -avz --delete --exclude=".*" ' + self.source + ' ' + self.destination);
    });
};
```

and then in the plugins section I add an instance of that as follows

```javascript
new RsyncPlugin('src/static', 'public')
```

**Comment by skeary-immt** [comment]
Unless I'm misunderstanding, you can do something like the following in one of your JS files:

```javascript
require.context('.', true, /\.png$/);
```
This above will require via webpack all png files in the same directory as the JS file. You then need to configure in the file loader in your webpack config file to do the actual copying:

```javascript
...
module: {
      loaders:  [
        {
          test: /\.png$/,
          loader: "file-loader?name=[path][name].[ext]"
        }
      ]
    },
...
```
The signature of require.context is:
```javascript
require.context(directory, useSubdirectories = false, regExp = /^\.\//)
```
See https://webpack.github.io/docs/context.html for more info.

**Comment by SpaceK33z** [comment]
Yeah what @skeary-immt said is the best way to fix this. Note that webpack isn't really intended to be used this way, hence the code is a bit ugly.
