### ISSUE TITLE
Ignore file output

### ISSUE THREAD

**Issue by kevinsimper** [webpack/file-loader#59]
Hi

I love this plugin but in a isomorphic app you don't want the server-side app to generate the images, but you still want the correct url of the resource.

I searched but I could not find any solution, so I forked this module and then just deleted the line that saves the file.

I published it as `ignore-file-loader`. https://github.com/kevinsimper/ignore-file-loader/

**Comment by elyobo** [comment]
@kevinsimper I've added a PR which resolves this by making it optional instead of removing it entirely.
