### ISSUE TITLE
Motivation for using file/url-loader

### ISSUE THREAD

**Issue by papigers** [webpack/file-loader#72]
I'm kind of a newbie to url/file-loader and webpack in general. Just wanted to know, what is the advanges of using file loader against just "sourcing" as usual?
i.e. `<img src={include(./logo.png)} >` VS `<img src="path/to/assets/logo.png" >`
Also is there a way avoid using ".. /.. /.. /logo.png" if I want to keep all my assets in one folder on the project's root?
Thanks!

**Comment by FredyC** [comment]
You can surely define alias for your folder with images.

I find generally easier to use loader as it can act as form of validation for your build. If your image is missing, it will complain. With just regular "sourcing" you wont get this advantage. Also another good thing is when you output your image with hash in its name. That will enforce cache busting whenever image content changes. With static file names some of your users might see old version of image till it's renewed in cache.

**Comment by SpaceK33z** [comment]
@FredyC explained this very well, so closing.
