### ISSUE TITLE
Change filename/extension in previous loader

### ISSUE THREAD

**Issue by glebmachine** [webpack/file-loader#76]
Hi @sokra!

I have writting new loader, which will be replace non-alpha png files to jpg (due image size optimization)
So, could you help me, please, to find a way to change the resource extension.

I have tried to do it  in a loader as follows:
```js
this.resourcePath = this.resourcePath.replace(/.png$/,'.jpg');
this.resource = this.resource.replace(/.png$/,'.jpg');
```

but, file-loader still emits '*.png' file...

And as usual, thank you in advance!)

**Comment by glebmachine** [comment]
As i understand loaderContext is separated between loaders, so i can't change context for `file-loader` from previous loader :(

**Comment by glebmachine** [comment]
Found it works in webpack 2.0

**Comment by sokra** [comment]
yeah... but you shouldn't do this...

better do this: 

``` js
{
  test: /\.png$/,
  loader: "file-loader?name=[hash].jpg!png2jpg-loader"
}
```

**Comment by glebmachine** [comment]
This loader more complex under the hood and easy-to-use at the same time.
Please, take a look here: https://github.com/glebmachine/image-optimize-loader
