### ISSUE TITLE
image map require error

### ISSUE THREAD

**Issue by Hazantip** [webpack/file-loader#83]
Please, help to solve the current problem.

Node version:
6.2.2
npm version:
3.9.0
Operating system:
win10
Steps to reproduce:
map list with images. problem with image src={require(image)}
`
const images = props.postcardImages.map((image, i) => { return ( <li classname="postcards-list-item" onclick="{()" ==""> {props.setPostcardActiveImage(image);}} key={image + i}> <link to="/postcard-edit"> <img src="{require(image)}" alt=""/> </link> </li> ); }); 
`
image - string with image path. if i put just string(not variable) it works fine, but i need to map it. when i try to do this staff i get the error:
Uncaught Error: Cannot find module '../images/postcard.jpg'.(anonymous function) @ Uncaught TypeError: Cannot read property '__reactInternalInstance$f26nyhc5w3kdfida23zph9f6r' of null

so i cant to pass into require variable, just a direct string path. but how i can map a many images with different pathes.

Config:
output: {
    path: `${__dirname}/src`, 
     publicPath: '/', 
    filename: 'bundle.js'
  },
	resolve: {
		root: path.resolve('./src')
	},
{test: /\.(jpe?g|png|gif)$/i, loaders: ['file']},

**Comment by SpaceK33z** [comment]
If you search on "webpack require dynamic", you'll get many helpful articles. Also see https://github.com/webpack/webpack/issues/118.

Closing this issue since it is not a problem in file-loader.
