### ISSUE TITLE
[Question]public path configuration

### ISSUE THREAD

**Issue by JanEggers** [webpack/file-loader#94]
hi,

im having problems with setting up the correct public path configuration.

i use this settings:

```
{
   test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
   loader: "file-loader?name=/wwwroot/bundles/fonts/[name].[ext]&publicPath=../"
}
```

the output is placed in /wwwroot/bundles/font, that is what i desire. 

But the public path that is used for refrences is ../wwwroot/bundles/fonts/ but what i need is /bundles/fonts/.

what do i need to configure to make it work that way?

**Comment by SpaceK33z** [comment]
See #81.

**Comment by JanEggers** [comment]
thx for pointing me there
