### ISSUE TITLE
I want to ask How this parameter to use in file-loader? Can anyone help

### ISSUE THREAD

**Issue by JQChan** [webpack/file-loader#95]
![image](https://cloud.githubusercontent.com/assets/7911342/19345256/24d1b40c-9170-11e6-97b5-888893cf9095.png)

**Comment by JQChan** [comment]
![image](https://cloud.githubusercontent.com/assets/7911342/19345567/660618d6-9171-11e6-9fb9-8b7309dc4d82.png)

I want to use the parameter in webpack loaders  config

**Comment by JQChan** [comment]
@sokra can you give me some help?

**Comment by shri3k** [comment]
@JQChan I see that you're using `url-loader` instead of `file-loader`. I don't think `regExp` query is available in `url-loader` (I might be wrong) but if you're indeed trying to look for `regExp` in `file-loader` then you can use it as:

```js
{ 
  test: /\.png$/,
  loader: 'file',
  query: {
    name: '[0]/[name].[ext]', // [N] is the grouping "N" of the match.
    regExp: 'some regex pattern here' //this has to be string surprisingly
}
```

**Comment by JQChan** [comment]
It helps me a lot. Thanks! @shri3k
