### ISSUE TITLE
Why is it copying my assets to dist folder?

### ISSUE THREAD

**Issue by Jorenm** [webpack/file-loader#97]
My code is compiling and working, but the file loader module is copying my assets into dist and then not even using them. The urls it resolves are to the original file locations, so its just bloating my dist folder for no apparent reason. Here's my config:

```
entry: path.resolve(__dirname, 'app', 'app.jsx'),
	output: {
		path: path.resolve(__dirname, "bin"),
		filename: 'app.bundle.js'
	},
	stylus: {
		use: [require('axis')(), require('nib')(), require('jeet')(), require('rupture')()],
		import: [
			path.resolve(__dirname, 'node_modules/nib/lib/nib/index.styl'),
			path.resolve(__dirname, 'node_modules/jeet/stylus/jeet/_jeet.styl')
		]
	},
	module: {
		loaders: [{
			test: /\.js$/,
			exclude: /(node_modules|bower_components)/,
			loader: 'babel-loader',
		}, {
			test: /\.jsx$/,
			exclude: /(node_modules|bower_components)/,
			loader: 'babel-loader',
			query: {
				presets: ['react']
			}
		}, {
			test: /\.styl$/,
			loaders: ['style-loader', 'css-loader', 'stylus-loader?resolve url'],
		}, {
			test: /\.css$/,
			loaders: ['style-loader', 'css-loader']
		}, {
			test: /\.(gif|png|jpg|svg|ttf|eot|woff|woff2)$/,
			loader: 'file?name=/wp-content/plugins/testplugin/[path][name].[ext]'
		}]
	},
```

**Comment by shri3k** [comment]
@Jorenm I'm not sure if this is your complete `webpack.config.js` but the line at 
`loader: 'file?name=/wp-content/plugins/testplugin/[path][name].[ext]'`
is telling it to copy all the image and fonts files to `/wp-content/plugins/testplugin`. `?name` particularly suggests that you want to copy file to the provided path.

**Comment by Jorenm** [comment]
I don't really understand how this all works. If I take out the file loader then it fails to compile the css, but if I leave it in the it copies files around which I do not want. How do I get it to resolve the file paths for the css file, while leaving the files alone?

**Comment by shri3k** [comment]
If you want it not to copy files then you can probably do:-
`loader: 'file?emitFile=false`

I'll try my best to give you a brief explanation on what's going on (even though I'm fairly new to this too).   `css-loader` is mostly responsible for converting `url` and `import` in your `css` to `require` that `node` understands and when you move down the pipe of `file-loader` it scans the file again and sees that you want images to be handled by `file-loader` and it processes all the "required" images and tries to copy them in the path you specify. 
You can tell `webpack` to copy them in specific path with `?name` query and that's what's it's doing in your case. Copying them is default behavior but you can turn them off as well with the one that I mentioned above.

Also, if you want it to just work then you can use [`url-loader`](https://github.com/webpack/url-loader) instead too. `url-loader` tries to add the content `inline` on js file.

**Comment by Jorenm** [comment]
Cool emitFile worked. Trying to figure out how this all works, I tried taking off the whole ?name= statement and it set the path in the css file to a hash, and the image got output as a hash in my dist folder. The problem is the image doesn't load because it doesn't put the path to the dist folder in the css file. Am I supposed to set some global path to my dist folder somewhere?

**Comment by shri3k** [comment]
By default if you don't specify `name` query then it uses `hash` as filename with the right extension and puts it in the `context` of `webpack.config.js` which again you can edit. By default, I think `context` is your current working directory. So whenever webpack creates these hashes it also modifies the path to your original file (which is css file in our case). That path should technically match with your site's "public" or "static" directory that serves static file. Let's say your app is hosting your `static` file in `/static` route so if you don't put your `images` or assets in that directory then your app will show up with `404`. I think that's whats happening in your case. I'm just guessing though.
